name: Monitor Updates

on:
  schedule:
    - cron: "*/5 * * * *" # 5분마다 실행
  workflow_dispatch: # 수동 실행도 가능하도록 설정

jobs:
  monitor-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Run Monitor
        run: |
          cd backend
          node monitor.js
