name: Update LCK Rankings

on:
  workflow_dispatch: # Dispatch 이벤트로 실행
  schedule:
    - cron: "*/30 * * * *" # 기본 실행 (예: 30분마다)

jobs:
  update-rankings:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          cd backend
          npm install

      # 4. Firebase 설정 파일 처리
      - name: Set up Firebase credentials
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $FIREBASE_CONFIG > backend/config/lolprogg-ed60f-firebase-adminsdk-1cerz-46615cd137.json

      # 5. 서버 실행 및 스크래핑 API 호출
      - name: Run server and scrape
        run: |
          cd backend
          node app.js &
          SERVER_PID=$!

          sleep 10
          curl -X GET http://localhost:3000/scrape

          kill $SERVER_PID
