name: Update LCK Rankings

on:
  schedule:
    - cron: "30 19 * * 3,4,5" # 수, 목, 금 19:30에 실행
    - cron: "0 22 * * 3,4,5" # 수, 목, 금 22:00에 실행
    - cron: "30 17 * * 6,7" # 토, 일 17:30에 실행
    - cron: "0 20 * * 6,7" # 토, 일 20:00에 실행

jobs:
  update-rankings:
    runs-on: ubuntu-latest

    steps:
      # 1. 저장소 코드 체크아웃
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.js 환경 설정
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      # 3. 의존성 설치
      - name: Install dependencies
        run: |
          cd backend/scraper
          npm install

      # 4. Firebase 설정 파일 처리
      - name: Set up Firebase credentials
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: |
          echo $FIREBASE_CONFIG > backend/config/firebaseConfig.js

      # 5. Scraper 실행
      - name: Run scraper
        run: |
          cd backend/scraper
          node scraper.js
